# -*- coding: utf-8 -*-
"""Calcular volume disponivel tirando o cilindro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FD1AvD7rWtZ-6UZZKT2pxhZY4o6RmNrK

#Nesse software, apresento uma solução para calcular o volume de um paralelepípedo que tem um cilindro centralizado ocupando volume. Vou descobrir quanto de volume disponível eu tenho.
"""

from math import pi

#Primeiro vou descobrir o volume do paralelepípedo:
altura_paralelepipedo = float(input('Digite a altura do paralelepípedo: '))
comprimento_paralelepipedo = float(input('Digite o comprimento do paralelepípedo: '))
largura_paralelepipedo = float(input('Digite a largura do paralelepípedo: '))

volume_paralelepipedo = altura_paralelepipedo * comprimento_paralelepipedo * largura_paralelepipedo

#Agora vou descobrir o raio do cilindro
raio_Cilindro = altura_paralelepipedo / 2

#Agora vou descobrir o volume do cilindro
volume_Cilindro = altura_paralelepipedo * pi * raio_Cilindro ** 2

#Agora vou calcular o volume util:
volume_Util = volume_paralelepipedo - volume_Cilindro
print(f'O volume que ptemos disponivel é: {volume_Util:.2f}')