# -*- coding: utf-8 -*-
"""Software-Calculo_IMC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKv2Vu1ieFhCeBRFwl58INBJkaa2YIoq

# Cálcular o IMC
"""

peso = float(input('Digite o seu peso: '))
altura = float(input('Digite a sua altura: '))

calculo = peso / (altura**2)

print(f'Com o peso de {peso}, e altura de {altura}')
print(f'Seu IMC atual é de: {calculo:.2f}')